name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy to server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/ubuntu/fastapi-book-project
            git pull origin main
            sudo fuser -k 8000/tcp || true
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker build -t fastapi-app:latest .
            docker run -d -p 8000:8000 --name fastapi-app fastapi-app:latest
            sudo systemctl restart nginx
          EOF
          rm -f private_key
